language: scala

scala:
   - 2.11.7

jdk:
- oraclejdk7

#script:
#  - sbt clean coverage test

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/45cb5820ca70c8a3445e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
