site_name: DynaML User Guide
site_dir: 'site'
site_description: 'User guide and documentation for the DynaML machine learning library and API'
site_author: 'Mandar Chandorkar'
site_url: 'https://transcendent-ai-labs.github.io/DynaML'
copyright: 'Copyright &copy; 2015 Mandar Chandorkar'
pages:
    - 'DynaML': index.md
    - 'Getting DynaML':
      - 'Installation': installation/installation.md
      - 'Import': installation/include.md
    - 'Supported Features': supported_features.md
    - 'Structure': structure.md
    - Releases:
      - 'v1.5.x':
        - 'v1.5.3': 'releases/mydoc_release_notes_153.md'
        - 'v1.5.2': 'releases/mydoc_release_notes_152.md'
        - 'v1.5.1': 'releases/mydoc_release_notes_151.md'
        - 'v1.5': 'releases/mydoc_release_notes_15.md'
      - 'v1.4.x':
        - 'v1.4.3': 'releases/mydoc_release_notes_143.md'
        - 'v1.4.2': 'releases/mydoc_release_notes_142.md'
        - 'v1.4.1': 'releases/mydoc_release_notes_141.md'
        - 'v1.4': 'releases/mydoc_release_notes_14.md'
    - Scaladoc:
      - v1.5.x:
        - v1.5.3:
          - dynaml-core: 'scaladoc/v1.5.3/core.md'
          - dynaml-pipes: 'scaladoc/v1.5.3/pipes.md'
          - dynaml-repl: 'scaladoc/v1.5.3/repl.md'
          - dynaml-examples: 'scaladoc/v1.5.3/examples.md'
        - v1.5.2:
            - dynaml-core: 'scaladoc/v1.5.2/core.md'
            - dynaml-pipes: 'scaladoc/v1.5.2/pipes.md'
            - dynaml-repl: 'scaladoc/v1.5.2/repl.md'
            - dynaml-examples: 'scaladoc/v1.5.2/examples.md'
        - v1.5.1:
            - dynaml-core: 'scaladoc/v1.5.1/core.md'
            - dynaml-pipes: 'scaladoc/v1.5.1/pipes.md'
            - dynaml-examples: 'scaladoc/v1.5.1/examples.md'
        - v1.5:
            - dynaml-core: 'scaladoc/v1.5/core.md'
            - dynaml-pipes: 'scaladoc/v1.5/pipes.md'
            - dynaml-examples: 'scaladoc/v1.5/examples.md'
      - v1.4.x:
        - v1.4.3:
            - dynaml-core: 'scaladoc/v1.4.3/core.md'
            - dynaml-pipes: 'scaladoc/v1.4.3/pipes.md'
            - dynaml-examples: 'scaladoc/v1.4.3/examples.md'
        - v1.4.2:
            - dynaml-core: 'scaladoc/v1.4.2/core.md'
            - dynaml-pipes: 'scaladoc/v1.4.2/pipes.md'
            - dynaml-examples: 'scaladoc/v1.4.2/examples.md'
        - v1.4.1:
            - dynaml-core: 'scaladoc/v1.4.1/core.md'
            - dynaml-pipes: 'scaladoc/v1.4.1/pipes.md'
            - dynaml-examples: 'scaladoc/v1.4.1/examples.md'
        - v1.4:
            - dynaml-core: 'scaladoc/v1.4/core.md'
            - dynaml-pipes: 'scaladoc/v1.4/pipes.md'
            - dynaml-examples: 'scaladoc/v1.4/examples.md'
    - 'User Guide':
      - 'Core':
        - Models:
          - Model Hierarchy: 'core/core_model_hierarchy.md'
          - Linear Models:
            - Generalized Linear Models: 'core/core_glm.md'
            - Generalized Least Squares: 'core/core_gls.md'
          - Stochastic Processes:
            - Gaussian Processes: 'core/core_gp.md'
            - Extended Skew Gaussian Processes: 'core/core_esgp.md'
            - Students T Processes: 'core/core_stp.md'
            - Multi-output Matrix T Process: 'core/core_multi_output_t.md'
          - Neural Networks:
            - Feed Forward Networks: 'core/core_ffn_new.md'
            - Neural Stack API: 'core/core_ann_new.md'
            - Old Neural Net API: 'core/core_ann.md'
          - Least Squares SVM: 'core/core_lssvm.md'
        - Tensorflow:
          - Introduction: 'core/core_dynaml_tf.md'
          - Tensorflow Pointer: 'core/core_dtf.md'
          - Building Blocks: 'core/core_dtflearn.md'
          - Data Set API: 'core/core_dtfdata.md'
          #- Utilities: 'core/core_tf_misc.md'
        - Kernels:
          - Kernel API: 'core/core_kernels.md'
          - Stationary Kernels: 'core/core_kernel_stat.md'
          - Non Stationary Kernels: 'core/core_kernel_nonstat.md'
          - Automatic Feature Extraction: 'core/core_kernel_nystrom.md'
        - Algebra:
          - Blocked Algebraic Objects: 'core/partitioned_objects.md'
          - Block Vectors: 'core/partitioned_vectors.md'
          - Block Matrices: 'core/partitioned_matrices.md'
          - Block Algebra Utilities: 'core/partitioned_alg_utils.md'
        - Probability:
          - Random Variables: 'core/core_prob_randomvar.md'
          - Operations on Random Variables: 'core/core_prob_operations.md'
          - Probability Distributions: 'core/core_prob_dist.md'
        - 'Optimizers & Solvers':
          - 'Convex': 'core/core_opt_convex.md'
          - 'Global': 'core/core_opt_global.md'
        - Graphics: 'core/core_graphics.md'
        - Performance Evaluation: 'core/core_model_evaluation.md'
      - 'Pipes':
        - 'DynaML Pipes': 'pipes/pipes.md'
        - 'Pipes API': 'pipes/pipes_api.md'
        - 'Scalers & Encoders': 'pipes/pipes_scalers_encoders.md'
        - 'Model Pipes': 'pipes/model_pipes.md'
        - 'DynaML Pipes Library':
          - 'String & File Processing': 'pipes/file_processing.md'
          - 'Feature Processing': 'pipes/feature_processing.md'
          - 'Time Series': 'pipes/pipes_time_series.md'
          - 'Workflows on Models': 'pipes/pipes_models.md'
          - Miscellaneuos: 'pipes/pipes_misc.md'
        - 'Pipes Example': 'pipes/pipes_library.md'
      - REPL Examples:
        - Examples Module: 'repl-examples/p2_examples.md'
        - Boston Housing: 'repl-examples/p2_boston_housing.md'
        - Wine Quality: 'repl-examples/p2_winequality_logistic.md'
        - Pont-sur-Sambre Power Plant: 'repl-examples/p2_lssvm_powerplant.md'
      - 'Misc. Utilities':
        - Data Transforms: 'utils/utils_data_transforms.md'
        - '`utils` object': 'utils/package.md'
    - 'License': 'license.md'
    - 'About Us': 'about.md'
    - DynaML Blog:
        - State of DynaML 2016: 'blog/2016-12-11-dynaml-new-features.md'
        - Resources for Beginners: 'blog/2016-12-08-getting-started-ml.md'
theme: material
theme:
  name: 'material'
  logo: 'images/dynaml_logo3_small.png'
  favicon: 'images/dynaml_logo3.png'
  palette:
    primary: 'teal'
    accent: 'green'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false, linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
repo_name: 'transcendent-ai-labs/DynaML'
repo_url: 'https://github.com/transcendent-ai-labs/DynaML'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
google_analytics:
  - 'UA-59996358-2'
  - 'auto'
extra:
  disqus: 'dynaml'
  social:
    - type: 'github'
      link: 'https://github.com/transcendent-ai-labs'
    - type: 'twitter'
      link: 'https://twitter.com/dyna_ml'

